### ISSUE TITLE
Problem reading names of picked up items

### ISSUE THREAD

**Issue by M-HT** [sdlpal/sdlpal#68] opened 2017-08-15 17:02 UTC
When an item is picked up, the name of the item is displayed. In the original DOS version, the name was displayed for a while and then disappeared without pressing any key. In sdlpal the name is displayed until a key is pressed. But when any key is pressed when displaying the name (for instance an arrow key), the name disappears really fast (because the pressed key is repeated) so I can't read the name of the item I picked up. The name disappears much faster than in the original DOS version.

Can this be fixed somehow ? Maybe setting a minimum time the name is displayed or allowing only kKeySearch and kKeyMenu to close the dialog with the name of the item ?

**Comment by palxex** [comment] 2017-08-15 17:57
Could you provide a operation list on reproducing?  I cannot get where the "pick up" you mean.

**Comment by M-HT** [comment] 2017-08-15 18:38
I mean for instance picking up the shoes at the beginning of the game:
![shoes](https://user-images.githubusercontent.com/12173952/29330474-90fc7494-81f9-11e7-9de1-898077db994f.png)

**Comment by oloukou** [comment] 2017-08-15 20:00
Verified the problem exist. I think the problem is caused by SDLPal processes key repeating differently than original DOS version( users can now just press the key to skip as much messages as he want, instead of only one screen in original version, AND since dialog/messages shares many logic, it also be skipped ), but seems its a good feature - for messages, at least. For both keeping the feature in messaging and avoid the problem in dialog, I think setup a minimum display time for dialog only is a better way. Just made a small patch for implementing it, please test whether it has side effect in unexpected way.

[dialog-repeat-patch.txt](https://github.com/sdlpal/sdlpal/files/1226220/dialog-repeat-patch.txt)

**Comment by palxex** [comment] 2017-08-15 20:03
Verified the problem exist. I think the problem is caused by SDLPal processes key repeating differently than original DOS version( users can now just press the key to skip as much messages as he want, instead of only one screen in original version, AND since dialog/messages shares many logic, it also be skipped ), but seems its a good feature - for messages, at least. For both keeping the feature in messaging and avoid the problem in dialog, I think setup a minimum display time for dialog only is a better way. Just made a small patch for implementing it, please test whether it has side effect in unexpected way.

[dialog-repeat-patch.txt](https://github.com/sdlpal/sdlpal/files/1226232/dialog-repeat-patch.txt)

**Comment by M-HT** [comment] 2017-08-15 20:39
I tested it a bit (and I'll test it more) and it works good, but I have a suggestion - in function PAL_DialogWaitForKeyWithinMinimalSeconds if a key is pressed, but the minimum display time has not passed, run PAL_ClearKeyState - that means that if I release all pressed keys before the minimum display time, the dialog will not close after the minimum display time (only when I press a key).

**Comment by palxex** [comment] 2017-08-15 21:03
OK...Let's try another patch that closer to original version.
[dialog-repeat-patch2.txt](https://github.com/sdlpal/sdlpal/files/1226437/dialog-repeat-patch2.txt)

**Comment by M-HT** [comment] 2017-08-16 19:29
I played the game with the new patch for a few hours and I didn't find any problems.

**Comment by palxex** [comment] 2017-08-16 21:01
Thanks for your testing:) committed.

**Closed** 2017-08-16 21:01 UTC
