### ISSUE TITLE
Display lag in android p

### ISSUE THREAD

**Issue by kinghtt** [sdlpal/sdlpal#108] opened 2018-09-07 01:05 UTC
Hi There,

I just flashed pixel experience 9.0 on my xiaomi mi 6 yesterday, and found that there is a definitely lag of display in the game.
It just look like no hardware acceleration in pc.
Maybe anything not compatible with the latest version of Android?

Thanks,
Eric

**Comment by kinghtt** [comment] 2018-09-07 13:38
仔细看了一下，不只是画面lag，人物移动之类的都极慢

**Comment by palxex** [comment] 2018-09-08 02:53
Currently I've not got any 9.0 compatible device. Not sure what happened.
You can try get log and post here, maybe its useful for digging reason - and future development. 
Hint: enable LOGFILE, and set LOGLEVEL to verbose. then enable GLSL filter backend, and use [plain.glsl](https://raw.githubusercontent.com/sdlpal/sdlpal/master/shaders/plain.glsl) as filter( in GLSL mode there're much more graphics relative logging made. and plain.glsl is almost identical to the original renderer, both on effects and performance) . Then launch the game - until you see the in-game trademark - then the logfile is available in your sdlpal folder.
Note: after logging finished, PLEASE turn down the logfile, and set LOGLEVEL back to default. Or the performance will be impacted more.
BTW: if you're using existing android release please write down the release version of SDLPal. Or if you're compiling from source, just post the logfile - revision is already included in log.
BTW2: Seems on android 8 there're two OpenGL ES renderer - one vanilla and another with skia backend. Not sure whether android 9 introduced more. You can try switch them in Developer Options and see whether it makes any performance improvement.

**Comment by kinghtt** [comment] 2018-09-08 03:09
may i know how to use glsl filter？

**Comment by kinghtt** [comment] 2018-09-08 03:29
[sdlpal.txt](https://github.com/sdlpal/sdlpal/files/2362976/sdlpal.txt)
Please refer to the attached txt file for the log using verbose mode. Seems that there is no errors included.
I checked and searched in developer options and found that there are no OPENGL mode switch related options available.
Let me describe the issues in detail as below for your reference.
When I started the game, the avi movies has a very large delay, and a part of the sound of the movie plays, but only a part of. Then after seconds, the movie graphic displays, but lags just like playing PPT.
It can keep playing, or I can skip it by pressing on any key.
When going to "新的故事，旧的回忆" page, nothing wrong.
When entering the game, the charactor(s) walking very slow, about 1 step only every 1-2 seconds.
When I use "esc" to enter the menu system, the speed seems normal.
Background music playing normally.
If you think it is useful, I can make a screen record (no voice because of the limit of Android system) and upload to youtube for you.

Thanks,
Eric

**Comment by palxex** [comment] 2018-09-08 03:34
If you could compile android apk, latest master already included GUI code for filter configure. Just place the glsl file in SDLPal folder and pick them in the new filter file picker - which will appear after GLSL Filter itself was enabled. You can also see temporary documents on https://github.com/PalMusicFan/sdlpal/wiki
You can also obtain the latest apk in  [latest nightly on bintray](https://dl.bintray.com/sdlpal/prereleases/v2018-08-22-g09baf56-master/). Note that on bintray we've multi development branch build, we only need result from master branch as demoed in the above URL, since development branches are actively testing and maybe removed/overwritten.

**Comment by kinghtt** [comment] 2018-09-08 03:54
[log.txt](https://github.com/sdlpal/sdlpal/files/2362993/log.txt)
Thanks for your reply. I enabled the filter and got a new log file which contains more info about opengl.
Hopefully it will be helpful.

**Comment by palxex** [comment] 2018-09-08 04:11
👍 great.
A few more questions:
1. After GLSL enabled, did you find the lagging has any change?
2. Do you have any other OpenGL ES games tested, are they also lagged? for example 崩坏3?

If both no, then we'd consider other reason for the lagging, maybe not relative to rendering.
BTW: android 8 Renderer selection UI as below:
![screenshot_ _20180908-121001](https://user-images.githubusercontent.com/58222/45250169-3576a380-b360-11e8-8517-0c61dd9c0c99.png)

**Comment by kinghtt** [comment] 2018-09-08 05:54
Confirmed that the latest version of 崩坏3 on google play running peefectly with no lag.

**Comment by palxex** [comment] 2018-09-08 08:31
Another Pie tester gggswc reports his device does not suffers SDLPal performance slowdown.
His device info:
![fe76f82e6aa483e86e9c67d0588ab675](https://user-images.githubusercontent.com/58222/45251979-e3df1080-b381-11e8-8b0e-1c888ff0ad08.jpg)
Consideration of the performance enhancement is not very much on Mi8 compares to Mi6 ( CPU 10%, GPU 30% ), and many low-end devices does able to afford SDL2 rendering, it also possible a temporary problem of Mi-6 Android Pie dev-channel porting. Lets' observe whether next release resolves it. You may also report it to MIUI developers.

**Comment by kinghtt** [comment] 2018-09-08 08:33
i'm using pixel experience rom. Hmmm...

**Comment by palxex** [comment] 2018-09-08 08:40
Oh, I misunderstood your word. Then you need to report to builder of this ROM.

**Comment by palxex** [comment] 2018-09-08 11:32
The problem is not whether MIUI is heavily modded, but "Android 9 seems making break changes", while it does not claims. Which is unusual, so a strong proof is needed.
Another questionable direction: test any other SDL1-eventloop game on your current ROM, like those from http://libsdl-android.sourceforge.net, to ensure whether problem occurs from this direction( Android Pie changed event system and this makes problem ). If so, please try whether research branch helps( latest nightly at https://dl.bintray.com/sdlpal/prereleases/v2018-09-01-g7c7467d-research/ )
Waiting your test result.

**Comment by kinghtt** [comment] 2018-09-08 12:42
i tried reseaech branch, no luck.
Will try some other sdl based games a bit later and give you a reply.

**Comment by kinghtt** [comment] 2018-09-08 13:09
i tested a game named supertux from the link you provided, very smooth with no lag...

**Comment by kinghtt** [comment] 2018-09-09 02:09
can it be a timer issue?

**Comment by palxex** [comment] 2018-09-09 02:35
Not sure. You can try modify SDL_Delay source code and verify it.
Another approach: In research branch, you can touch top-left area on screen to trigger debug output( touch again to close it; current implementation cost much CPU on rendering those info), includes FPS and some other rendering detail. Could you capture screen let me know how it be on your device?

**Comment by kinghtt** [comment] 2018-09-09 03:04
![screenshot_20180909-122850](https://user-images.githubusercontent.com/8971067/45260656-06c5ff00-b42c-11e8-91f4-3b8a1f89f8a1.png)
Please refer to the screenshot for the details.
The fps is flashing which made it not able to be shown on the screenshot, but I saw it changing between 0fps(when 李逍遥 is standing) to 45fps(when 李逍遥 is moving).
Since as I said that he can only move 1 step every second, the fps is 0 in most of the time.
The candle on the desk is not flashing if 李逍遥 is not moving, only flashing when he is moving.
It means that if there is no action from user, all the items on the map will not move.
The yellow texts on the menu (新的故事，旧的回忆 and 系统，物品，仙术 etc）is not shining either.

**Comment by kinghtt** [comment] 2018-09-12 05:12
It is confirmed as a kernel issue.
Previously the kernel was 4.4.153, which has this issue.
I updated it to 4.4.154, it works fine.
So please feel free to close this issue.
Thanks.

**Closed** 2018-09-12 10:02 UTC
