### ISSUE TITLE
LineageOS Loading Data Issue

### ISSUE THREAD

**Issue by kinghtt** [sdlpal/sdlpal#86] opened 2018-05-20 01:47 UTC
i just found that when I am using lineageos 14.1, there is an issue on loading game data files.
I set the sdlpal folder under sdcard directory, and using the in-app settings to point the data directory to there, then it works. but after the session of sdlpal is killed or the phone is rebooted, though the in-app settings are still correct, it will return an error on opening data files. I need to redirect in sdlpal app (though nothing is changed) then save settings, and it work again. it happens every time and is confirmed not a random issue.
thanks.

**Comment by louyihua** [comment] 2018-05-20 05:13
This seems to be a permission related issue.
What exact steps did you take when you are redirected into the setting page again to make it work on the next start?

**Comment by palxex** [comment] 2018-05-24 13:03
I've experience this problem several times too. Not sure where causes the problem and whether stock ROM has same problem - since my device don't have stock ROM on this version :(
Steps to reproduce on my device (oneplus one bacon, lineage 14.1, 7.1.2):
0. reboot, or deploy a new debug apk.
1. open app, it complains fbp.mkf not found. select Launch settings dialog on next start.
2. check permissions, verified the storage permission is already granted.
3. close it, reenter, now settings activity pops up. click Done - complains no game resource found.
4. open "browse" of GamePath, opens File Picker. CHANGE NOTHING, and click Confirm in File Picker.
5. click Done again in Settings. This time everything OK, game launches.

In my situation, reboot will 100% trigger it; but simple kill the app then reopen it will never trigger it, unless a new apk is deployed - also in memory, this method not 100% trigger it. Not sure whether 7.1.2 or lineage related.

**Comment by palxex** [comment] 2018-05-31 18:04
After some digging, it seems a bug on system level ( still unsure related with LineageOS or AOSP, needs more test ).
The behavior is: after reboot, though the sdcard permission was still granted, anyfile WITHOUT ACCESSED BY JAVA CODE will not work in native file operation.
Made a hack commit that works on my device, please test whether works on your too.

**Comment by palxex** [comment] 2018-06-01 07:11
@kinghtt Try uninstall old build before installing. This is a debug build, signing key is different.

**Comment by palxex** [comment] 2018-06-01 14:13
Test result on OnePlus 3T 8.0 stock ROM is same. So it seems really sdcardFS compatible problem with NDK only games, not problem of SDLPal. Please report to google.

**Closed by palxex** 2018-06-01 14:13 UTC
