### ISSUE TITLE
Application crashes possibly related to PAL_swprintf?

### ISSUE THREAD

**Issue by PalMusicFan** [sdlpal/sdlpal#4] opened 2017-02-21 03:16 UTC
When an item is stolen, LEVEL UP, etc, the application crashes. 

"Unhandled exception at 0x7734C6D1 in sdlpal.exe: 0xC00001A5: 偵測到無效的例外處理常式。 (parameters: 0x00000003)."

"Exception thrown: write access violation.
dest was 0x152F000.
If there is a handler for this exception, the program may be safely continued."

Environment: 
VS2015, SDL2.0.5, Windows10.

**Comment by palxex** [comment] 2017-02-21 03:39
Confirmed in mingw/vs2017 win32 build,  28e3b94

**Comment by palxex** [comment] 2017-02-21 06:36
@louyihua maybe we'd better introduce a unit test framework; or refactoring seems way too dangerous.

**Comment by louyihua** [comment] 2017-02-21 07:17
@PalMusicFan @palxex 
The crash for stealing items should be caused by a missing `PAL_GetWord` in cb732e7.

And I agreed that there should be a unit test framework. Maybe we can start from enforcing unit test code for any newly added/refacted codes.

**Comment by palxex** [comment] 2017-02-21 08:06
@louyihua Confirmed stealing item resolved, but I still need modify code to remove all the "/ sizeof(WCHAR)" or it will still crash( VS2017 RC/msys2 mingw-w64/OSX ). Could you please make the other two bugfix and commit?

**Comment by louyihua** [comment] 2017-02-21 11:10
@PalMusicFan @palxex 
It's my fault. Caused by the change of the type of `precision`. Fixed in ccd9202.

**Closed** 2017-02-21 11:12 UTC
