### ISSUE TITLE
How to install uwp version？

### ISSUE THREAD

**Issue by kinghtt** [sdlpal/sdlpal#116] opened 2018-10-28 00:17 UTC
Hi there, I just tried to install the latest nightly build (10.27 master) of uwp version on win 10 2018.9 version.
It says that I need a new certificate to install it. I tried to import the cert inside the zip file to the whole computer (I am sure that I use the admin privilege to do everything), but seems it doesn't work.
Could you please guide?

Thanks,
Eric

**Comment by palxex** [comment] 2018-10-28 07:17
0. open `Developer Options` in `Settings`/`Update and Security`, change deploy mode from `Microsoft Store Only` to `Developer Mode`.
1. extract `sdlpal-uwp.zip` to a folder.
2. enter that folder, find `Add-AppDevPackage.ps1`, right click on it, then select `run with powershell` in popup menu.
3. follow instruments the ps1 script asks. It may change local `execution policy`, so UAC may popup, just let it go. It will also asks you to install ad-hoc certificate( all sideload UWP that does not distributed through windows store needs it ), just let it go too. After both, the script will start to install SDLPal UWP and all its requirements. Wait it done and enjoy.

Troubleshoots:
1. If you ever tried build and debug your own SDLPal UWP version, it will deny the side-load version from installing. Uninstall it first - just find it in start menu/cortana and right click uninstall.
2. If you ever tried install certificate but installed to wrong zone, you may still facing problem. Just uninstall it and let the script install it.
3. If you still facing problem, let us know.

**Comment by kinghtt** [comment] 2018-10-28 10:17
Please refer to the screenshot for the error message. It seems to be a midi package error.
![qq 20181028204610](https://user-images.githubusercontent.com/8971067/47614621-af224680-daf2-11e8-95a5-7e6793b3dab3.png)

**Comment by palxex** [comment] 2018-10-28 10:55
Please give me result of 
```
Get-AppxPackage -Name microsoft.midi.gmdls
```
in `powershell`.
Seems maybe an upgraded version preinstalled in 1809. The solution will either be disabling install the bounded one( but unsure whether it will works with the upgraded one - not sure ABI stability ), either uninstalling the preinstalled one.

**Comment by kinghtt** [comment] 2018-10-28 11:29
delete the appx file works, thank you.

**Comment by kinghtt** [comment] 2018-10-28 11:30
but i just found that no midi music playing during the game is running. Also, the control is a but delay than exe version.

**Comment by palxex** [comment] 2018-11-03 08:32
@PalMusicFan noticed me that MIDI in UWP version is silent only under Pal Win95 resource. Previous I've only tested with DOS ver and thought the problem not exist. Sorry @kinghtt , reopened.

**Comment by palxex** [comment] 2018-11-03 13:05
The win95 resource MIDI not play problem should be fixed int 784b44b. Please test on 1809 and verify whether the MIDI works well now - on latest nightly.

**Comment by palxex** [comment] 2018-11-06 14:32
Closed due to lack of response. Reopen if the problem confirmed not fixed.

**Closed by palxex** 2018-11-06 14:32 UTC
Labels: bug
